CREATE LOGIN [Vernon]
    WITH PASSWORD = N'o>pj|ph:lme3yd|lqYwPjuxumsFT7_&#$!~<smb@+KD<w+my', SID = 0xA7FC05F8E37ACB42AAAA8F201E2FF369, DEFAULT_DATABASE = [Sandbox], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

